dist: xenial
language: python
python:
  - "3.6"

cache: pip

branches:
  only:
    - main

addons:
  apt:
    packages:
      - pandoc
install:
#  - pip install pandoc==2.2.3
  - pip install nbconvert
  - pip install Sphinx
  - pip install nbsphinx
  - pip install ipykernel
  - pip install sphinx_rtd_theme
  - pip install lxml
  - pip install beautifulsoup4
  - pip install numpy
  - pip install pandas
  - pip install matplotlib
  - pip install scikit-learn
  - pip install scipy
  - pip install seaborn

script:
  - python -m sphinx . _build/ -b html
  - ./add_html_anchors_to_exercises.py _build/*.html
  - touch _build/.nojekyll # this file tells gh-pages that there is no need to build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: _build
  target-branch: gh-pages
  on:
    branch: main

notifications:
  email:
    recipients:
      - saska.donges@helsinki.fi
    on_success: change
    on_failure: always
